# Generated by Django 4.1.4 on 2023-05-10 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0004_capture_delete_webcamimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
