# Generated by Django 4.1.4 on 2023-05-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0005_alter_courrier_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='fichier')),
            ],
        ),
    ]
