# Generated by Django 4.1.4 on 2023-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Universite',
            field=models.BooleanField(default=False, verbose_name='is_Universite'),
        ),
    ]
